- job:
    name: plugins-task-build
    parent: gerrit-plugin-build
    pre-run:
<<<<<<< HEAD
        tools/playbooks/install_docker.yaml
    vars:
        bazelisk_test_targets: "plugins/task/lint_test plugins/task/..."
        
=======
        - tools/playbooks/install_docker.yaml
        - tools/playbooks/install_python3-distutils.yaml

>>>>>>> stable-3.1
- project:
    description: |
      Build the plugin in check, and also build and publish it after
      every merged commit.
    check:
      jobs:
        - plugins-task-build
    post:
      jobs:
        - plugins-task-build
        - gerrit-plugin-publish:
            dependencies:
              - plugins-task-build
