- job:
    name: plugins-task-build
    parent: gerrit-plugin-build
    pre-run:
        tools/playbooks/install_dependencies.yaml

- project:
    description: |
      Build the plugin in check, and also build and publish it after
      every merged commit.
    check:
      jobs:
        - plugins-task-build
    post:
      jobs:
        - plugins-task-build
        - gerrit-plugin-publish:
            dependencies:
              - plugins-task-build
