- job:
    name: plugins-task-build
    parent: gerrit-plugin-build
    pre-run:
        tools/playbooks/install_docker.yaml
    vars:
        bazelisk_test_targets: "plugins/task/lint_test"

- project:
    check:
      jobs:
        - plugins-task-build
