- hosts: all
  tasks:
    - name: Install docker and docker-compose
      shell: |
        sudo apt install --assume-yes apt-transport-https ca-certificates curl gnupg2 software-properties-common
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
        sudo add-apt-repository --yes "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        sudo apt update --assume-yes
        sudo apt install --assume-yes docker-ce
        sudo usermod -aG docker ${USER}
        newgrp docker
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
